export interface ClassData {
  courseId: string,
  BookUsefulnessAvg: number,
  BookUsefulnessCount: number,
  ClassName: string,
  CourseNumber: string,
  DifficultyAvg: number,
  DifficultyCount: number,
  GraphicThumbnail: string,
  GraphicColor: string,
  GraphicUrl: string,
  LectureQualityAvg: number,
  LectureQualityCount: number,
  PiazzaCommunityAvg: number,
  PiazzaCommunityCount: number,
  ProfessorQualityAvg: number,
  ProfessorQualityCount: number,
  RatingAvg: number,
  RatingCount: number,
  Teacher: string,
  WorkloadAvg: number,
  WorkloadCount: number,
  category: string
  languages: string[] | null,
  meta: {[key: string]: boolean},
  season: {
    spring: boolean,
    summer: boolean,
    fall: boolean
  },
}
