on:
  push:
    branches: [ main ]
jobs:
  git-sync:
    name: Staging Push
    runs-on: ubuntu-latest
    uses: wei/git-sync@v3
    with:
      source_repo: MSCSHub/MSCSHub
      source_branch: main
      destination_repo: MSCSHub/MSCSHub-staging
      destination_branch: main
